#!/usr/bin/python

import os
import json
import cgi

config_location = '/var/www/authzor/authzor.conf'

def main():
    print "Content-type: application/json\n"
    
    # Get configuration values
    try:
        config_file = open(config_location)
    except IOError:
        print_error('Could not open the configuration file.')
        raise
    try:
        settings = json.loads(config_file.read())
    except ValueError:
        print_error('Could not parse the configuration file.')
        raise
   
    # Connect to SVN to get a list of repositories

    try:
        repo_names = (next(os.walk(settings['svn_root_dir'])))[1]
        repo_names.sort()
        print json.dumps(repo_names)
    except StopIteration:
        print_error('The specified SVN root directory does not exist.')
        raise
    
def print_error(error):
    print json.dumps({'error':error})
  
if __name__ == "__main__":
    main()
