#!/usr/bin/python
"""
Retrieve SVN root directory location from configuration
file, then return a list of the repositories it contains
"""
import os
import json

CONFIG_LOCATION = '../authzor.conf'


def main():
    """
    Get the path to the SVN root directory from the configuration
    file, then return a list of subdirectories
    """
    print "Content-type: application/json\n"

    try:
        config_file = open(CONFIG_LOCATION)
    except IOError:
        print_error('Could not open the configuration file.')
        raise
    try:
        settings = json.loads(config_file.read())
    except ValueError:
        print_error('Could not parse the configuration file.')
        raise

    try:
        repo_names = (next(os.walk(settings['svn_root_dir'])))[1]
        repo_names.sort()
        print json.dumps(repo_names)
    except StopIteration:
        print_error('The specified SVN root directory does not exist.')
        raise


def print_error(error):
    """Take a string and print a JSON object containing it."""
    print json.dumps({'error': error})

if __name__ == "__main__":
    main()
