#!/usr/bin/python
"""
Read configuration object in JSON format from STDIN
and write it directly to file. Then read it back
from file and write to STDOUT.
"""
import sys

CONFIG_LOCATION = '../authzor.conf'


def main():
    """
    Read configuration object from STDIN
    and write to file, then read from file and
    write back to STDOUT.
    """
    print 'Content-type: application/json\n'
    try:
        data = sys.stdin.read()
        if data != '':
            config_file = open(CONFIG_LOCATION, 'w')
            config_file.write(data)
            config_file.close()

        config_file = open(CONFIG_LOCATION)
        data = config_file.read()
        print data
    except IOError:
        print '{"error": "Could not open the configuration file."}'

if __name__ == '__main__':
    main()
